### ISSUE TITLE
Can't import .hex files

### ISSUE THREAD

**Issue by githubhero** [microbit-foundation/microbit-blue#1]
Hello, I tried to import your .hex files online in Pxt but they didn't work. 

I was interested in the APIs you use to communicate from the microbit (I could not find anything related to BLE)

**Comment by ghost** [comment]
Hi

the hex files in this repo were not created with PXT so importing them will not work, as you found.

If you're saying you're interested in the micro:bit APIs for Bluetooth then you could do worse than to take a look at the tutorials at http://www.bittysoftware.com/ 

Good luck
